server:
  port: 8088
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-headers: '*'
            allowed-methods: GET,POST,PUT,DELETE,OPTIONS
            allowed-origins: '*'
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s
      routes:
        -   id: user-service
            predicates:
              - Path=/api/users/**
            uri: http://localhost:8081
        -   id: employee-service
            predicates:
              - Path=/api/employees/**
            uri: http://localhost:8082
#          filters:
#            - RewritePath=/users/(?<segment>.*), /${segment}
#        - id: product_service_route
#          uri: http://localhost:8081
#          predicates:
#            - Path=/products/**
#          filters:
#            - AddRequestHeader=X-Custom-Header, MyValue

